- name: prepare | install required system packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-redis
      - valkey-server
      - valkey-tools
      - valkey-sentinel
- name: Copy valkey get-master script
  ansible.builtin.copy:
    src: scripts/{{item}}
    dest: /opt/cent/bin/
    mode: "0755"
  with_items:
    - common_redis.py
    - redis-get-master.py
- name: Stat transparent_hugepage
  ansible.builtin.stat:
    path: /sys/kernel/mm/transparent_hugepage/enabled
  register: valkeydb_transparent_hugepage
# Disable Transparent Huge Pages
- name: Inject kernel.mm.transparent_hugepage
  when: valkeydb_transparent_hugepage.stat.writeable
  ansible.builtin.shell:
    cmd: "echo never > /sys/kernel/mm/transparent_hugepage/enabled && touch {{ ansible_facts.env.HOME }}/.kernel.mm.transparent_hugepage.never"
    creates: "{{ ansible_facts.env.HOME }}/.kernel.mm.transparent_hugepage.never"
- name: Stat /etc/default/grub
  ansible.builtin.stat:
    path: /etc/default/grub
  register: valkeydb_grub
- name: Ensure auditing for processes that start prior to auditd is enabled 1/2 (configure grub)
  when: valkeydb_grub.stat.exists
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="console=tty1 console=ttyS0 transparent_hugepage=never"'
  register: grub
- name: Ensure auditing for processes that start prior to auditd is enabled 2/2 (update initrd image)
  ansible.builtin.shell:
    cmd: update-grub
  when: grub.changed
# Add reserved ports we use to the ephemeral range
- name: Reserve tcp ports in ephemeral port range
  when: ansible_facts.virtualization_type != "docker"
  ansible.builtin.sysctl:
    name: net.ipv4.ip_local_reserved_ports
    value: "36379-36479,46379-46479,56379-56479"
    state: present
    ignoreerrors: yes
# Enable vm.overcommit_memory, recommended by Valkey
- name: Enable vm.overcommit_memory
  when: ansible_facts.virtualization_type != "docker"
  ansible.builtin.sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
    ignoreerrors: yes
# Increase "net/core" subsys registered per network namespace
- name: Increase net.core.somaxconn
  when: ansible_facts.virtualization_type != "docker"
  ansible.builtin.sysctl:
    name: net.core.somaxconn
    value: 65535
    state: present
    ignoreerrors: yes
